Rerun last test
adamwathan/sublime-phpunit pull request #29
Opened 2017-05-17 09:44 UTC by timonSchenzel

Nice feature for rerun your last test from any other file within your project.

2017-06-06 07:09 UTC, lorisleiva commented
I was specifically looking for that feature. That would be amazing.

2017-07-04 17:51 UTC, DCzajkowski requested changes
I wanted to make a PR like this myself. It's awesome you have made it! Thanks and I hope it will be merged very soon. 😃

2017-07-04 17:51 UTC, DCzajkowski commented on sublime-phpunit.sublime-commands
> +]
The new line at the end of a file would be appreciated :)

2017-07-04 17:51 UTC, DCzajkowski commented on sublime-phpunit.py
> +            self.run_in_terminal('cd ' + phpunit_config_path + ' && phpunit ' + file_name + " --filter '/::" + current_function + "$/'")
Can you reuse existing implementation, ie run the method inside the `RunSinglePhpunitTestCommand` class? Maybe extend it and call the parent's `run()` method?

2017-08-07 13:27 UTC, timonSchenzel commented on sublime-phpunit.py
> +            self.run_in_terminal('cd ' + phpunit_config_path + ' && phpunit ' + file_name + " --filter '/::" + current_function + "$/'")
Good suggestion, I have reused existing implementation.

2017-08-07 13:28 UTC, DCzajkowski commented on sublime-phpunit.py
> +            self.run_in_terminal('cd ' + phpunit_config_path + ' && phpunit ' + file_name + " --filter '/::" + current_function + "$/'")
Awesome! I hope it will be merged very soon :)

2017-08-09 20:22 UTC, merged

2017-08-09 20:33 UTC, DCzajkowski commented
Woohoo! 🎉

2017-08-09 21:34 UTC, timonSchenzel commented
Nice! :smile: